### PR TITLE
added PSH and CLI scripts

### PR DESCRIPTION
**Pull request by cephalin**

### CODE REVIEW

**Comment by davidebbo** [comment]
The diff looks quite suspicious, showing every line in the templates having changed. This could be a sign of end-of-line corruption or something like that.

**Comment by cephalin** [comment]
In the course of my modifying the template to make sure it works with CLI, VS changed the spacing on every line. So I think that’s why GitHub got confused about the diffs.

**Comment by davidebbo** [comment]
Usually, it's best to address those issues before submitting the pull request. Otherwise, it's impossible to know what really changed. Generally, if the diff you see in the pull request doesn't exactly match what you changed, there are probable issues with it and it should not be merged.

**Comment by cephalin** [comment]
OK. Sorry about that. I ran them through my deployment scripts so many times though so there shouldn’t be any issues with them.

**Pull request merged**
